spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: work.liuting.pojo
  mapper-locations: classpath:dao/*.xml
server:
  port: 80
pagehelper:
  helper-dialect: mysql
  reasonable: true
